package com.example.data.remote

import com.example.BuildConfig
import com.example.data.local.AccessPassEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.json.JSONObject
import java.util.Locale
import java.util.concurrent.TimeUnit

data class TelegramBotSyncResult(
    val success: Boolean,
    val botUsername: String,
    val syncedPasses: List<AccessPassEntity>,
    val statusMessage: String
)

/**
 * Handles secure synchronization and code verification with the Telegram Bot (@KurdishFlim_4bot).
 *
 * Security & Sync Protocol:
 * 1. Reads TELEGRAM_BOT_TOKEN from BuildConfig (configured via AI Studio Secrets).
 * 2. Calls Telegram Bot API `/getMe` and `/getUpdates` to fetch bot-issued subscription codes
 *    and their assigned validity durations (e.g., 30d, 7d, 25d 12h) or revoke commands (`/revoke CODE`).
 * 3. Supports deterministic parsing of @KurdishFlim_4bot structured tokens (e.g., `KF-30D-XXXX`,
 *    `KF-7D-XXXX`, `KF-25D12H-XXXX`) so codes generated by the bot carry their exact validity duration.
 */
class TelegramBotSyncService {

    private val httpClient = OkHttpClient.Builder()
        .connectTimeout(10, TimeUnit.SECONDS)
        .readTimeout(12, TimeUnit.SECONDS)
        .build()

    fun isBotTokenConfigured(): Boolean {
        val token = BuildConfig.TELEGRAM_BOT_TOKEN.trim()
        return token.isNotEmpty() && token != "MY_TELEGRAM_BOT_TOKEN" && token.contains(":")
    }

    /**
     * Queries the Telegram Bot API (`getMe` and `getUpdates`) for @KurdishFlim_4bot
     * to pull any newly generated access codes and duration rules.
     */
    suspend fun syncPassesFromTelegramBot(): TelegramBotSyncResult = withContext(Dispatchers.IO) {
        val token = BuildConfig.TELEGRAM_BOT_TOKEN.trim()
        if (!isBotTokenConfigured()) {
            return@withContext TelegramBotSyncResult(
                success = false,
                botUsername = "@KurdishFlim_4bot",
                syncedPasses = emptyList(),
                statusMessage = "TELEGRAM_BOT_TOKEN not set in Secrets panel. Using local @KurdishFlim_4bot validation vault."
            )
        }

        try {
            val baseUrl = "https://api.telegram.org/bot$token"

            // 1. Verify bot identity via /getMe
            val meRequest = Request.Builder().url("$baseUrl/getMe").get().build()
            var verifiedBotHandle = "@KurdishFlim_4bot"
            httpClient.newCall(meRequest).execute().use { meResp ->
                if (meResp.isSuccessful) {
                    val body = meResp.body?.string().orEmpty()
                    val json = JSONObject(body)
                    if (json.optBoolean("ok")) {
                        val username = json.optJSONObject("result")?.optString("username").orEmpty()
                        if (username.isNotBlank()) {
                            verifiedBotHandle = "@$username"
                        }
                    }
                } else {
                    return@withContext TelegramBotSyncResult(
                        success = false,
                        botUsername = "@KurdishFlim_4bot",
                        syncedPasses = emptyList(),
                        statusMessage = "Telegram API HTTP ${meResp.code}: Check TELEGRAM_BOT_TOKEN in AI Studio Secrets."
                    )
                }
            }

            // 2. Fetch recent bot updates (/getUpdates) to extract generated codes & validity durations
            val updatesRequest = Request.Builder()
                .url("$baseUrl/getUpdates?limit=100&allowed_updates=%5B%22message%22,%22channel_post%22%5D")
                .get()
                .build()

            val discoveredPasses = mutableMapOf<String, AccessPassEntity>()
            val revokedCodes = mutableSetOf<String>()

            httpClient.newCall(updatesRequest).execute().use { upResp ->
                if (upResp.isSuccessful) {
                    val body = upResp.body?.string().orEmpty()
                    val root = JSONObject(body)
                    val results = root.optJSONArray("result")
                    if (results != null) {
                        for (i in 0 until results.length()) {
                            val updateObj = results.optJSONObject(i) ?: continue
                            val msgObj = updateObj.optJSONObject("message")
                                ?: updateObj.optJSONObject("channel_post")
                                ?: continue
                            val text = msgObj.optString("text", "").trim()
                            val msgDateSec = msgObj.optLong("date", System.currentTimeMillis() / 1000L)
                            val msgEpochMs = msgDateSec * 1000L

                            if (text.isNotEmpty()) {
                                parseBotMessageForCode(
                                    text = text,
                                    issuedAtEpochMs = msgEpochMs,
                                    botHandle = verifiedBotHandle,
                                    onPassFound = { pass -> discoveredPasses[pass.code] = pass },
                                    onRevokeFound = { code -> revokedCodes.add(code.uppercase(Locale.US)) }
                                )
                            }
                        }
                    }
                }
            }

            val finalPasses = discoveredPasses.values.map { pass ->
                if (revokedCodes.contains(pass.code)) {
                    pass.copy(isActive = false)
                } else {
                    pass
                }
            }

            TelegramBotSyncResult(
                success = true,
                botUsername = verifiedBotHandle,
                syncedPasses = finalPasses,
                statusMessage = "Synced with $verifiedBotHandle (${finalPasses.size} bot updates processed)"
            )
        } catch (e: Exception) {
            TelegramBotSyncResult(
                success = false,
                botUsername = "@KurdishFlim_4bot",
                syncedPasses = emptyList(),
                statusMessage = "Telegram sync offline (${e.localizedMessage ?: "Network error"}). Local @KurdishFlim_4bot verifier active."
            )
        }
    }

    /**
     * Parses messages sent in @KurdishFlim_4bot chat:
     * Supported patterns:
     * - `/gen KF-30D-9981 30d` or `/code MYCODE 7d`
     * - `CODE: KF-7D-2026 | DURATION: 7d`
     * - Any self-describing bot token pattern like `KF-30D-XXXX`, `KF-7D-XXXX`, `KF-25D12H-XXXX`
     * - `/revoke CODE` or `/block CODE`
     */
    private fun parseBotMessageForCode(
        text: String,
        issuedAtEpochMs: Long,
        botHandle: String,
        onPassFound: (AccessPassEntity) -> Unit,
        onRevokeFound: (String) -> Unit
    ) {
        val trimmed = text.trim()

        // Check for revoke command
        val revokeRegex = Regex("""(?i)^/(?:revoke|block|ban)\s+([A-Z0-9_-]{4,32})""")
        revokeRegex.find(trimmed)?.let { match ->
            onRevokeFound(match.groupValues[1].uppercase(Locale.US))
            return
        }

        // Check for /gen or /add or /code command: e.g. `/gen KURD-VIP-101 30d`
        val cmdRegex = Regex("""(?i)^/(?:gen|add|code|new)\s+([A-Z0-9_-]{4,32})(?:\s+(\d+)\s*([dhm]))?""")
        cmdRegex.find(trimmed)?.let { match ->
            val code = match.groupValues[1].uppercase(Locale.US)
            val amount = match.groupValues[2].toLongOrNull()
            val unit = match.groupValues[3].lowercase(Locale.US)
            val durationMs = if (amount != null && amount > 0) {
                when (unit) {
                    "d" -> amount * 24L * 3600_000L
                    "h" -> amount * 3600_000L
                    "m" -> amount * 60_000L
                    else -> amount * 24L * 3600_000L
                }
            } else {
                extractEmbeddedDurationMs(code) ?: (30L * 24L * 3600_000L)
            }

            onPassFound(
                AccessPassEntity(
                    code = code,
                    planName = "KurdishFlim Bot Pass (${formatDurationShort(durationMs)})",
                    holderName = "Telegram User",
                    validityDurationMs = durationMs,
                    activatedAtEpochMillis = issuedAtEpochMs,
                    expiryEpochMillis = issuedAtEpochMs + durationMs,
                    maxResolution = "4K HDR • KurdishSub",
                    botSource = botHandle,
                    isAdmin = false,
                    isActive = true
                )
            )
            return
        }

        // Check for embedded KF-<DURATION>-<KEY> tokens inside message text
        val tokenRegex = Regex("""\b(KF-(?:\d+D(?:\d+H)?|\d+H|\d+M|\d+S)-[A-Z0-9]{3,12})\b""", RegexOption.IGNORE_CASE)
        tokenRegex.findAll(trimmed).forEach { match ->
            val rawToken = match.groupValues[1].uppercase(Locale.US)
            val durationMs = extractEmbeddedDurationMs(rawToken) ?: (30L * 24L * 3600_000L)
            onPassFound(
                AccessPassEntity(
                    code = rawToken,
                    planName = "KurdishFlim Bot Pass (${formatDurationShort(durationMs)})",
                    holderName = "Telegram Subscriber",
                    validityDurationMs = durationMs,
                    activatedAtEpochMillis = 0L, // Activated on first entry in app
                    expiryEpochMillis = System.currentTimeMillis() + durationMs,
                    maxResolution = "4K HDR • KurdishSub",
                    botSource = botHandle,
                    isAdmin = false,
                    isActive = true
                )
            )
        }
    }

    /**
     * Parses a @KurdishFlim_4bot formatted code if it embeds a duration signature:
     * Examples:
     * - `KF-30D-8821` -> 30 days
     * - `KF-7D-VIP9` -> 7 days
     * - `KF-25D12H-VIP` -> 25 days and 12 hours
     * - `KF-15S-LOCK` -> 15 seconds (for testing instant auto-lock)
     */
    fun extractEmbeddedDurationMs(code: String): Long? {
        val upper = code.trim().uppercase(Locale.US)
        val daysHoursRegex = Regex("""^(?:KF|KURD)-(\d+)D(?:(\d+)H)?-[A-Z0-9]{2,14}$""")
        daysHoursRegex.find(upper)?.let { match ->
            val days = match.groupValues[1].toLongOrNull() ?: return null
            val hours = match.groupValues[2].toLongOrNull() ?: 0L
            return (days * 24L * 3600_000L) + (hours * 3600_000L)
        }

        val hoursOnlyRegex = Regex("""^(?:KF|KURD)-(\d+)H-[A-Z0-9]{2,14}$""")
        hoursOnlyRegex.find(upper)?.let { match ->
            val hours = match.groupValues[1].toLongOrNull() ?: return null
            return hours * 3600_000L
        }

        val minsOnlyRegex = Regex("""^(?:KF|KURD)-(\d+)M-[A-Z0-9]{2,14}$""")
        minsOnlyRegex.find(upper)?.let { match ->
            val mins = match.groupValues[1].toLongOrNull() ?: return null
            return mins * 60_000L
        }

        val secsOnlyRegex = Regex("""^(?:KF|KURD)-(\d+)S-[A-Z0-9]{2,14}$""")
        secsOnlyRegex.find(upper)?.let { match ->
            val secs = match.groupValues[1].toLongOrNull() ?: return null
            return secs * 1000L
        }

        return null
    }

    fun formatDurationShort(durationMs: Long): String {
        val totalSecs = durationMs / 1000L
        val days = totalSecs / 86400L
        val hours = (totalSecs % 86400L) / 3600L
        return when {
            days > 0 && hours > 0 -> "${days}d ${hours}h"
            days > 0 -> "${days} Days"
            hours > 0 -> "${hours} Hours"
            totalSecs >= 60 -> "${totalSecs / 60} Mins"
            else -> "${totalSecs}s"
        }
    }
}
